---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base
patches:
  - target:
      group: operators.coreos.com
      kind: Subscription
      version: v1alpha1
    path: patch-channel.yaml

