apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../operator/overlays/eus-2.16
  - ../../../instance/overlays/eus-2.16-nvidia-gpu
patches:
  - patch: |-
      - op: replaceAdd commentMore actions
        path: "/metadata/name"
        value: rhods-operator
    target:
      kind: OperatorGroup
      name: rhods-operator-group