apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../operator/overlays/eus-2.16
  - ../../../instance/overlays/eus-2.16-nvidia-gpu
patches:
  - patch: |-
      - op: replace
        path: "/metadata/name"
        value: rhods-operator
    target:
      kind: OperatorGroup
      name: rhods-operator-group
  - patch: |-
      - op: replace
        path: "/metadata/name"
        value: default-dsc
    target:
      kind: DataScienceCluster
      name: default
  - path: patch-datascience-cluster.yaml
    target:
      kind: DataScienceCluster
      name: default-dsc
